# Generated by Django 4.2.2 on 2023-07-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empexpense',
        ),
    ]
